### System of linear equations

* System of linear equations in the form a_0x + a_1x + ... + a_n-1x = b_0
* Simplied to matrix Ax = b
    * A is matrix with dimensions i,j of linear coefficients
    * b is 1D array of constants



### Gaussian elimation
* Basic method:
    * Create augmented matrix with A and b to form [A|b]
    * Reduce matrix down to reduced row echelon form 

In [1]:
import numpy as np 

a = np.array([[1,1,1],[1,2,4],[1,3,9]])
# print(a)
a_transpose = a.T  # for transpose
# print(a_transpose)

b = np.array([1, -1, 1])
# print(b)

# two methods of creating the augmented matrix
# augmented = np.c_[a,b]
augmented = np.column_stack([a,b])
print(augmented)

# basic solver algorithms:
# 0. Swap rows as needed (if leading row is 0)
# 1. multiply row by a non zero constant
# 2. add multiple of one row to another

x = np.linalg.solve(a,b)
print(x)

[[ 1  1  1  1]
 [ 1  2  4 -1]
 [ 1  3  9  1]]
[ 7. -8.  2.]


### LU factorization
* Easier to resolve for a new b matrix
* break A matrix into A = LU 

$\begin{align}
A = 
\begin{pmatrix}
    4 & 3 & 2 \\
    16 & 14 & 9 \\
    12 & 13 & 13
\end{pmatrix}
= \qquad \;
\begin{pmatrix}
    1 & 0 & 0 \\
    4 & 1 & 0 \\
    3 & 2 & 1
\end{pmatrix} \qquad \;
\begin{pmatrix}
    4 & 3 & 2\\
    0 & 2 & 1\\
    0 & 0 & 5
\end{pmatrix}
= L U
\end{align}$

* L is lower triangular with 1s on diagonal
* U is upper triangular with pivots on main diagonal
* can be stored as single array
    * no need to store diagonal 1s from L 
    * store off diagonal elements of L diagonal of U

$A x = b \iff L U x = b \iff L y = b$ where $U x = y$

- Factor: $A \rightarrow L U$
- Solve $L y = b$
- Solve $U x = y$

### PLU factorization
* Extra step of conducting row swaps in order to minimize non diagonal values
* large diagonal values can result in numerical errors
<br> $ A = PLU$



In [2]:
# LU example
U = np.array([[4,3,2],[0,2,1],[0,0,5]])
L = np.array([[1,0,0],[4,1,0],[3,2,1]])

A = np.dot(L,U)
print(A)

det = np.linalg.det(A)
print(det)

[[ 4  3  2]
 [16 14  9]
 [12 13 13]]
40.0


In [3]:
# LU decomposiiton example
import scipy.linalg

P, L, U = scipy.linalg.lu(a)  # (P, L, U)
print(P)  # permutation matrix to keep track of any necessary row swaps. has only single 1 in each row and column. 
print(L)  # lower matrix
print(U)  # upper matrix

a_check = np.dot(L, U)  # verify LU decmoposition was successful
print(a_check)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1.  0.  0. ]
 [1.  1.  0. ]
 [1.  0.5 1. ]]
[[ 1.  1.  1.]
 [ 0.  2.  8.]
 [ 0.  0. -1.]]
[[1. 1. 1.]
 [1. 3. 9.]
 [1. 2. 4.]]


In [ ]:
# LU decomposition and solve
# this is much more efficient for large matrix then solving directly if solution for multiple b matricies must be computed

lu, piv = scipy.linalg.lu_factor(a)
b = np.array([1, -1, 1])  # example b solution
print(piv)
print(lu)  # combines L and U matricies into single matrix per notes above

x = scipy.linalg.lu_solve((lu, piv), b)  # x from Ax = b
print(x)

### Iterative soltution methods for Ax = b
1. Make an initial guess for x(0)
2. Given a guess x(k), compute an improved solution 
3. Repeat until stopping criteria
    * change is small
    * residual error is small
    * number of iterations has reached set number

**Jacobi iteration** 

1. Solve each row/equations for the corresponding solution
2. Plug in previous soltuions to the next
<br> This involves solving for matrix inverse, but that is okay since invert is diagonal


In [ ]:
# jacobi example
a = np.array([[1,1,1],[1,2,4],[1,3,9]])
b = np.array([1, -1, 1])
print(a)
print(b)

In [ ]:
# jacobi update function
def jacobi_update(x, y, z):
    x_new = 1 -y -z
    y_new = (-1 -x -4*z)/2.
    z_new = (1-x-3*y)/9.
    return x_new, y_new, z_new

In [ ]:
# repeat iterations of jacobi update
iters = 20

# intial guess
x, y, z = 1., 2., 2.
data = np.zeros([iters, 4])  # matrix to hold data from all iterations
for k in range(iters):
    data[k, 0] = k
    data[k, 1] = x
    data[k, 2] = y
    data[k, 3] = z
    x, y, z = jacobi_update(x, y, z)
print(data)


**Diagonal dominance:**
<br> the issue here and reason it did not approach zero is because the magnitude of diagonal values is larger than sum of other coefficients in the row
<br> **solution:** use a better update technique

### Gauss-Seidel iteration
* Same as jacobi update, but uses new terms as they become available

In [ ]:
# jacobi update function
def gauss_seidel_update(x, y, z):
    x_new = 1 -y -z
    y_new = (-1 -x_new -4*z)/2.
    z_new = (1-x_new-3*y_new)/9.
    return x_new, y_new, z_new

In [ ]:
# repeat iterations of jacobi update
iters = 20

# intial guess
x, y, z = 1., 2., 2.
data = np.zeros([iters, 4])  # matrix to hold data from all iterations
for k in range(iters):
    data[k, 0] = k
    data[k, 1] = x
    data[k, 2] = y
    data[k, 3] = z
    x, y, z = gauss_seidel_update(x, y, z)
print(data)
