In [ ]:
import numpy as np

# Numpy package: actually stored in C
Array1 = np.ndarray([1, 2, 3]) # float
Array2 = np.array([1, 3, 5]) # int
Array3 = np.empty([2,1]) # But need to define all indicies first!
Array3[:,0] = 3
Array4 = np.zeros([1,4])
Array5 = np.ones([4,2])
Array6 = np.eye(3)
Array7 = np.arange(1,10,2) # (start, end, increment)
# Attributes
att1 = np.shape(Array5) # dimensions # output is (4,2)
att2 = np.size(Array5) # total number of elements # output is 8 

In [7]:
import numpy as np

# basic math in numpy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# addition
z0 = x+y
print(z0)

# scalar multiplication
z1 = 3*x
print(z1)

# dot product
z2 = np.dot(x, y)
print(z2)


[5 7 9]
[3 6 9]
32


In [11]:
import numpy as numpy

# range in numpy creates a numpy array with the desired range
x = np.arange(11)
print(x)

y = np.arange(0, 11, 1)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
import numpy as np

# create a better range np.linspace(start, stop, n values)
x = np.linspace(0, 1, 6)
print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
import numpy as np

# create a matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# indexing values matrix[column, row]
value_0 = A[1,2] # this should index value 6
print(value_0)

# create transpose of matrix
# these both create the same
B = np.transpose(A)
C = A.T
print(B)
print(C)

# find dimentions of matrix
dimensions = A.shape
print(dimensions)

In [26]:
import numpy as np 

# more matrix
# for complex number use j
A = np.array([[1, 2],[3, 4j]])
print(A)

# complex conjugate
B = np.conjugate(A)
print(B)

C = np.dot(A, B)
print(C)
D = np.cross(A,B)
print(D)

[[1.+0.j 2.+0.j]
 [3.+0.j 0.+4.j]]
[[1.-0.j 2.-0.j]
 [3.-0.j 0.-4.j]]
[[ 7. +0.j  2. -8.j]
 [ 3.+12.j 22. +0.j]]
[0. +0.j 0.-24.j]
