## Random Numbers

- Psudo random numbers with ```random``` module
- Actually random numbers with ```secrets``` module
- Random arrays with ```numpy```

In [4]:
import random

a = random.random()  # random float from 0 -> 1

b = random.uniform(1,10)  # random float in this range

c = random.randint(1, 10)  # random int in this range

d = random.normalvariate(mu=0, sigma=1)  # random from normal distribution with mean at 0 and SD of 1

print(d)


2.415243957353889


In [7]:
import secrets

a = secrets.randbelow(10)  # random int in range 0 to 10 (10 not included)

b = secrets.randbits(4)  # random number from 0 to 15

list = list("ABCDEFG")
c = secrets.choice(list)  # random choice from list
print(c)

C


In [10]:
import numpy as np

a = np.random.rand(3)  # array with 3 random floats

b = np.random.randint(0, 10, size=(3,3))
print(b)

[[1 9 1]
 [1 5 8]
 [1 0 9]]
