# numpy

Scientific computation module.

Tips:
1. When manipulating data, convert to np array once and stay in numpy. Dont convert back to other python data format with python built-ins.
    - Use np.max instead of max().

In [1]:
import numpy as np

In [2]:
# Numpy package: actually stored in C
Array1 = np.ndarray([1, 2, 3]) # ndarray
Array2 = np.array([1, 3, 5]) # array with ints
Array3 = np.empty([2,1]) # But need to define all indicies first!
Array3[:,0] = 3
Array4 = np.zeros([1,4])
Array5 = np.ones([4,2])
Array6 = np.eye(3)
Array7 = np.arange(1,10,2) # (start, end, increment)
# Attributes
att1 = np.shape(Array5) # dimensions # output is (4,2)
att2 = np.size(Array5) # total number of elements # output is 8 

In [3]:
# basic math in numpy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# addition
z0 = x+y
print(z0)

# scalar multiplication
z1 = 3*x
print(z1)

# dot product
z2 = np.dot(x, y)
print(z2)


[5 7 9]
[3 6 9]
32


In [ ]:
# range in numpy creates a numpy array with the desired range
x = np.arange(11)
print(x)

y = np.arange(0, 11, 1, dtype='float64')  # (start, stop, step)
print(y)

In [ ]:
# create a better range np.linspace(start, stop, n values)
x = np.linspace(0, 1, 6)
print(x)

In [4]:
# create a matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# indexing values matrix[column, row]
value_0 = A[1,2] # this should index value 6
print(value_0)

# create transpose of matrix
# these both create the same
B = np.transpose(A)
C = A.T
print(B)
print(C)

# find dimentions of matrix
dimensions = A.shape
print(dimensions)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


### Array slicing: 
To access subarrays for working on rows or columns (or any subarray)
* slice notation uses ":"
* for array x
* for array $x$
* $x[start:stop:step]$
* use $-step$ to swap start and stop
* For multi dimention arrays
    * $x[dimension1, dimension2, dimension3, ...]$
    * $x[start:stop:step, start:stop:step, ...]]$]
    * For 2D $x[row, column]$

**Note:** This only returns a view of the elements. 
* If you modify a sub assembly, the original assembly is ALSO modified!
* To get a copy and modify without impacting original
    * use $.copy()$

In [5]:
x = np.arange(10)

print(x[:5])  # first 5 elements. This notation only uses the stop element
print(x[0:5:1])  # same as above
print(x[5:])  # print elements after 5
print(x[4:7:1])  # print index 4 through 7
print(x[::2]) # print every other

print(x[::-1])  # reverse array

[0 1 2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [44]:
# accessing rows or columns
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

print(x2)
print(x2[:, 0])  # print every row of column 0
print(x2[0, :])  # print row 0, every column


[[2 8 6 0]
 [8 0 1 8]
 [7 3 2 0]]
[2 8 7]
[2 8 6 0]


In [41]:
# accessing slices or parts of array

print(x2)
print(x2[:2, :3])  # print up until 2 rows and up until 3 columns
print(x2[1:3:1, 2:4:1])  # print out array from rows[1:3] and columns[2:4]

[[4 9 5 0]
 [4 5 8 9]
 [6 0 6 6]]
[[4 9 5]
 [4 5 8]]
[[8 9]
 [6 6]]


In [ ]:
# use .copy() to create a seperate array

print(x2)
x2_new = x2[:, 0].copy()
print(x2_new)

### Reshaping, concatenation, and splitting
**Resphaping**
* row vectors via np.reshape()
* column vector via np.reshape((3, 1))
* column vector via np.newaxis()

**Concatenation:** (joining matrices)
* np.concatenate()
* np.vstack()  # vertical stack (easier for mixed dimensions)
* np.hstack()  # horizontal stack
8 np.dstack()  # along the third axis



In [54]:
# reshaping

x = np.array([1, 2, 3])
print(x.reshape((1, 3)))  # row vector
print(x.reshape((3, 1)))  # column vector
print(x[:, np.newaxis])  # column vector

[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [63]:
# concatenate

y = np.array([4, 5, 6])
z1 = np.concatenate([x, y])  # combine into single row
print(z1)
z2 = np.concatenate([[x], [y]])
print(z2)

a = np.random.randint(10, size=(3, 3))
print(a)
z3 = np.vstack([a, y])  # stack a on top of y
print(z3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[4 3 6]
 [7 1 2]
 [5 2 4]]
[[4 3 6]
 [7 1 2]
 [5 2 4]
 [4 5 6]]


In [45]:
# 

x2[[0, 1]] = x2[[1,0]]
print(x2)

[[8 0 1 8]
 [2 8 6 0]
 [7 3 2 0]]


In [ ]:
# more matrix
# for complex number use j
A = np.array([[1, 2],[3, 4j]])
print(A)

# complex conjugate
B = np.conjugate(A)
print(B)

C = np.dot(A, B)
print(C)
D = np.cross(A,B)
print(D)

In [ ]:
# appending
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, 0, 1.5, 0, 0, 1.7])

res = []
for i in range(len(b)):
     if b[i] > 0:
        res.append([a[i], b[i]])
res = np.array(res)
print(res)

In [ ]:
# Polynomial best fit line

Temp = np.array([320, 360, 400, 440, 480])
TempK = Temp + 273.15
v = np.array([26.82, 30.89, 34.32, 37.42, 40.34])

# polynomial 2nd order
dvdT = np.polyfit(TempK, v, 2)
print(dvdT)

# take derivative of polynomial
derivative_dvdT = np.polyder(dvdT)
print(derivative_dvdT)

# evaluate at the polynomial at T = 400C = 673.15 K
T_eval = 673.15
v_eval = np.polyval(derivative_dvdT, T_eval)
print(v_eval)

In [ ]:
import sympy

x = sympy.symbols('x')  # set x to be symbolic variable
sympy.plot(sympy.exp(x)-sympy.tan(x),(x,-10,10), ylim=(-5,5))

# sympy makes symbolic plotting easy, but hard to manipulate values
# use numpy instead!

In [ ]:
import matplotlib.pyplot as plt

n = 250
x = np.linspace(-10, 10, n)
y = np.zeros(n)

for i in range(n):
    y[i] = np.exp(x[i]) - np.tan(x[i])  # compute desired function
    
    if abs(y[i] > 10):
        y[i] = np.inf  # replacevalues greater than 10 with infinity

plt.plot(x,y)
plt.axis([-10,10,-5,5])
plt.xlabel('x')
plt.ylabel('f(x) = exp(x)-tan(x)')
plt.grid(True)
# plt.savefig("figure.png")  # save figure to file
plt.show()

In [ ]:
# root finding
# bracket on left and right of interest range to see when signs changs

# 1. pick left and right values
xl = -4.  # left start of interval interval
xr = -2.8  # right start or interval

# 2. set number iterations for resultion
iter = 1000
resolution = 1e-5  # precision of answer

# 3. Evaluate function at those values
for i in range(iter):
    xc = (xl + xr)/2  # compute midpoint
    fc = np.exp(xc) - np.tan(xc)
    print(i, xc, fc)

    if fc > 0:
        xl = xc
    else:
        xr = xc

    if (abs(fc) < resolution):
        break

print('root is at x =', xc)

In [ ]:
# newton raphson iteration method
x=-4 #initial estimate of fixed point
max_iter = 1000
for j in range(max_iter):
    x = x-(np.exp(x)-np.tan(x))/(np.exp(x)-(1/np.cos(x))**2)
    f=np.exp(x)-np.tan(x)
    
    if abs(f)<1e-5:
        break

print('root is near',x,'where function value is',f)

In [ ]:
# exporting with numpy
a = np.array([0, 1, 2])

np.savetxt(fname='savedinfo.txt', X=a, fmt='%d')

# fname is file name
# X is array to save
# fmt is data format %d is int, %1.4e is 4 decimal places

In [ ]:
importedfile = np.genfromtxt(fname='savedinfo.txt', dtype=np.float32)
print(importedfile)